# Generated by Django 5.2.6 on 2025-09-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BagPage', '0001_initial'),
        ('StockPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='bag_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='StockPage.item', to_field='item_code'),
        ),
    ]
