# Generated by Django 5.2.6 on 2025-09-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_code',
            field=models.CharField(default='ec939c47a6', editable=False, max_length=36, unique=True),
        ),
    ]
