# Generated by Django 5.2.6 on 2025-09-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0002_alter_card_card_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterField(
            model_name='card',
            name='card_code',
            field=models.CharField(default='ea75f8574a', editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(default='greeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='card',
            table=None,
        ),
    ]
