# Generated by Django 5.2.6 on 2025-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0003_alter_card_options_alter_card_card_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_code',
            field=models.CharField(default='7493bc259c', editable=False, max_length=36, unique=True),
        ),
    ]
