# Generated by Django 5.2.6 on 2025-09-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0004_alter_card_card_code'),
        ('StockPage', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='StockPage.item', to_field='item_code'),
        ),
    ]
