# Generated by Django 5.2.6 on 2025-09-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0005_alter_card_card_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='purchase_price',
            new_name='card_price',
        ),
        migrations.RemoveField(
            model_name='card',
            name='selling_price',
        ),
    ]
