# Generated by Django 5.2.6 on 2025-09-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardPage', '0006_rename_purchase_price_card_card_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
    ]
