# Generated by Django 5.2.6 on 2025-10-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=500)),
                ('PanNumber', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('AlternateMobileNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('TaxPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
