# Generated by Django 5.2.6 on 2025-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceUpdatePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedatamodel',
            name='GstNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
