# Generated by Django 5.2.6 on 2025-10-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvoiceUpdatePage', '0002_basedatamodel_gstnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedatamodel',
            name='PanNumber',
        ),
    ]
