# Generated by Django 5.2.6 on 2025-09-28 15:39

import StockPage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BagPage', '0001_initial'),
        ('CardPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(default=StockPage.models.generate_item_code, editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BagsStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=None, null=True)),
                ('reorder_level', models.IntegerField(default=None, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='BagPage.bag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardsStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.IntegerField(default=None, null=True)),
                ('reorder_level', models.IntegerField(default=None, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='CardPage.card')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
