# Generated by Django 5.2.6 on 2025-09-23 11:11

import StockPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(default=StockPage.models.generate_item_code, editable=False, max_length=20, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
            ],
        ),
    ]
