# Generated by Django 5.2.6 on 2025-09-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockPage', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsstock',
            name='unit',
        ),
    ]
