# Generated by Django 5.2.6 on 2025-09-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPage', '0003_remove_cardsstock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsstock',
            name='reorder_level',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='cardsstock',
            name='stock_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
